# Custom Language File for Launcher Customizer

[ejs.app]
title = "DevBubble Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS MOJANG"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum servidor selecionado"
launchDetails = "Aguarde.."

[ejs.loginOptions]
loginOptionsTitle = "Opções de Login"
loginWithMicrosoft = "Entrar com Microsoft"
loginWithMojang = "Entrar com Mojang"
loginOfflineDev = "Entrar Offline (Dev)"
cancelButton = "Voltar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Início"
tabAccountHeaderText = "Configurações da Conta"
minecraftTabHeaderText = "Configurações do Minecraft"
tabModsHeaderText = "Configurações de Mods"
tabJavaHeaderText = "Configurações do Java"
launcherTabHeaderText = "Configurações do Launcher"
aboutTabHeaderText = "Sobre"
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.overlay]
offlineNameTitle = "Nome do jogador offline"
offlineNameDesc = "Escolha o nome que será usado pelo seu perfil local de testes"
offlineNameConfirm = "Confirmar"
offlineNameCancel = "Cancelar"

[js.auth.offline]
usernamePrompt = "Escolha o nome do jogador offline para os testes"

[ejs.welcome]
welcomeHeader = "WELCOME TO WESTEROSCRAFT"
welcomeDescription = "Our mission is to recreate the universe imagined by author George RR Martin in his fantasy series, A Song of Ice and Fire.  Through the collaborative effort of thousands of community members, we have sought to create Westeros as accurately and precisely as possible within Minecraft.  The world we are creating is yours to explore.  Journey from Dorne to Castle Black, and if you aren’t afraid, beyond the Wall itself, but best not delay.  As the words of House Stark ominously warn: Winter is Coming."
welcomeDescCTA = "You are just a few clicks away from Westeros."
